# Generated by Django 5.0.6 on 2024-06-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('NIN', models.CharField(max_length=100)),
                ('dejaVote', models.BooleanField(default=False)),
            ],
        ),
    ]
